### ISSUE TITLE
Portal docker build fails with ProvenanceUI error

### ISSUE THREAD

**Issue by maxsibilla** [sennetconsortium/provenance-ui#12]
Build locally with latest Provenance UI produces the following error.  Succeeds randomly 1/10 times.

<img width="678" alt="image" src="https://github.com/sennetconsortium/provenance-ui/assets/7218802/74636077-cf05-4eef-9585-0ce4ff6434de">

**Comment by libpitt** [comment]
@maxsibilla 
Builds in docker locally. The warning doesn't cause it to not build.

The dependency issue is caused because:

`import (`../ProvenanceUI.css`)`

Is compiled to:

`Promise.resolve('../ProvenanceUI.css').then(s => _interopRequireWildcard(require(s)));`

Instead of:

`Promise.resolve(`../ProvenanceUI.css`).then(s => _interopRequireWildcard(require(`${s}`)));`

Could probably just update this manually after next build of ProvenanceUI to avoid seeing this warning. Or update the babel settings or plugin.
